trigger:
- master

pool:
  name: my_agent_pool

steps:
- task: DotNetCoreCLI@2
  displayName: "Compilación"
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    workingDirectory: '$(System.DefaultWorkingDirectory)/SandboxProf'

- task: DotNetCoreCLI@2
  displayName: "Publicación"
  inputs:
    command: 'publish'
    publishWebProjects: true
    workingDirectory: '$(System.DefaultWorkingDirectory)/SandboxProf'

- task: AzureRmWebAppDeployment@5
  displayName: "Despliegue"
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Azure subscription 1(f5346de4-af56-4396-a0e4-188bce1d0bcb)'
    appType: 'webApp'
    WebAppName: 'ManualAzure'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'